const all = [
    'Ax throwing',
    'Amazon shopping',
    'Beach trip',
    'Baking',
    'Bible study',
    'Bread making',
    'Birmingham trip',
    'Botanical gardens',
    'Camping',
    'Cooking',
    'Canoeing',
    'Coffee making',
    'Chess',
    'Card games',
    'Dancing',
    'Fighting games',
    'Fruit picking',
    'Feed ducks',
    'Guitar',
    'Guessing games',
    'Hiking',
    'Horseback riding',
    'Honeymoon planning',
    'Kayaking',
    'Laser tag',
    'Museum trip',
    'Movie night',
    'Movie trip',
    'Minecraft',
    'Netflix',
    'Obstacle course',
    'Painting',
    'Paddle boarding ',
    'Photo shoot',
    'Picnic',
    'Pizza making',
    'Pottery making',
    'Puzzles' ,
    'Rock climbing',
    'Reorganize / redecorate',
    'Read',
    'Run',
    'Stardew Valley',
    'Stargazing',
    'Sharing memes',
    'Thrifting',
    'Tea making',
    'Volunteering',
    'Yoga',
    'Yard sale',
    'Youtube',
    'Zoo'
]
const loweffort = [
    'Amazon shopping',
    'Bible study',
    'Coffee making',
    'Card games',
    'Guessing games',
    'Honeymoon planning',
    'Movie night',
    'Minecraft',
    'Netflix',
    'Read',
    'Stardew Valley',
    'Sharing memes',
    'Tea making',
    'Youtube',
]
const higheffort = [
    'Baking',
    'Bread making',
    'Cooking',
    'Chess',
    'Dancing',
    'Fighting games',
    'Guitar',
    'Painting',
    'Pizza making',
    'Puzzles',
    'Reorganize / redecorate',
    'Run',
    'Yoga',
]
const goingout = [
    'Ax throwing',
    'Beach trip',
    'Birmingham trip',
    'Botanical gardens',
    'Camping',
    'Canoeing',
    'Fruit picking',
    'Feed ducks',
    'Hiking',
    'Horseback riding',
    'Kayaking',
    'Laser tag',
    'Museum trip',
    'Movie trip',
    'Obstacle course',
    'Paddle boarding ',
    'Photo shoot',
    'Picnic',
    'Pottery making',
    'Rock climbing',
    'Stargazing',
    'Thrifting',
    'Volunteering',
    'Yard sale',
    'Zoo'
]

export {all, loweffort, higheffort, goingout}